### ISSUE TITLE
Не работает ивент с книгами

### ISSUE THREAD

**Issue by medovi40k** [Iaiao/GPclone#1]
![image](https://user-images.githubusercontent.com/74722105/108833960-94870c00-75de-11eb-9d04-6665914af43c.png)
При шифте и нажатии правой кнопки ничего не происходит

**Comment by Iaiao** [comment]
Нужно держать в руке документ (книгу с серым названием, которую написал юрист) и шифт+пкм по автору книги (в описании книги его имя)
