### ISSUE TITLE
Есть ли рюкзаки?

### ISSUE THREAD

**Issue by Gleb4uk123** [Iaiao/GPclone#3]
Работает ли в плагине OnlyHands рюкзаки? Например когда одеваешь нагрудник то добавляются слоты

**Comment by Iaiao** [comment]
Нет, такого нет, не знаю почему забыл, но обновлять этот репозиторий я не буду (максимум баги фиксить) т.к. это я по приколу спидранил создание сборки с ужасным качеством, а не реальная нормальная сборка.

**Comment by Gleb4uk123** [comment]
ну блин
